disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - type_body_length

opt_in_rules:
  - closure_end_indentation
  - indentation_width
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - multiline_arguments_brackets
  - multiline_arguments
  - vertical_parameter_alignment_on_call

excluded:
  - Pods
  - SwiftUIGraphQLDemo/API.swift

# Disable build error on long line lengths, but give warnings
line_length: 120

# Disable build error on big files, keep warnings
file_length: 400

# Warn about short variable names, but allow certain exceptions for common
# loop names
identifier_name:
  min_length: 3
  max_length: 40
  excluded: ["i", "j", "k"]
